[build]
  publish = "."
  command = ""

[[headers]]
  for = "/v2/app.jsx"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/shared/components.jsx"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
